---
- name: Converge
  hosts: all
  become: true

  vars:
    sentry_db_name: 'sentry'
    sentry_db_user: 'sentry'
    sentry_secret_key: 'SAFE'
    postgres_repo_version: '9.5'
    postgresql_databases:
      - name: '{{ sentry_db_name }}'
        owner: '{{ sentry_db_user }}'
    postgresql_users:
      - name: '{{ sentry_db_user }}'
        role_attr_flags: SUPERUSER
    postgresql_hba_entries:
      - {type: local, database: all, user: postgres, auth_method: peer}
      - {type: local, database: all, user: '{{ sentry_db_user }}', auth_method: trust}

  pre_tasks:
    - name: Enable EPEL repo on EL for Redis role
      yum: pkg=epel-release state=present
      when: ansible_os_family == 'RedHat'
    - name: Install cron (RedHat).
      yum: name=cronie state=present
      when: ansible_os_family == 'RedHat'

  tasks:
    - import_role:
        name: geerlingguy.redis
    - import_role:
        name: Duologic.postgresql_repository
    - import_role:
        name: geerlingguy.postgresql
    - meta: flush_handlers
    - import_role:
        name: pascal_splotches.sentry

  post_tasks:
    - name: Wait for Sentry to leave the runway
      wait_for:
        port: 9010
        delay: 30
